apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-hello
  template:
    metadata:
      labels:
        app: spring-boot-hello
    spec:
      containers:
        - name: spring-boot-hello
          image: ganesh/spring-boot-hello:latest
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
spec:
  type: NodePort
  selector:
    app: spring-boot-hello
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30090